name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensures all submodules are cloned

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin mkdocs-mermaid2-plugin mkdocs-section-index mkdocs-autolinks-plugin mkdocs-macros-plugin pymdown-extensions

      - name: Deploy MkDocs to GitHub Pages
        run: |
          mkdocs gh-deploy --force
