CREATE DATABASE smart_time_registration;
USE smart_time_registration;

CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Role VARCHAR(100)
);

CREATE TABLE Cards (
    CardID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    RFID_Tag VARCHAR(255) UNIQUE NOT NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    IssueDate DATE,
    ExpiryDate DATE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE WorkSessions (
    SessionID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    ClockInTime DATETIME NOT NULL,
    ClockOutTime DATETIME,
    TotalHours FLOAT GENERATED ALWAYS AS (TIMESTAMPDIFF(SECOND, ClockInTime, ClockOutTime) / 3600) STORED,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE AttendanceLogs (
    LogID INT AUTO_INCREMENT PRIMARY KEY,
    CardID INT NOT NULL,
    Timestamp DATETIME NOT NULL,
    EventType ENUM('Clock In', 'Clock Out') NOT NULL,
    FOREIGN KEY (CardID) REFERENCES Cards(CardID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE InternalTemperature (
    TempLogID INT AUTO_INCREMENT PRIMARY KEY,
    Timestamp DATETIME NOT NULL,
    Temperature FLOAT NOT NULL
);

